version: "3"
services:
  server:
    image: daos_server
    tty: true
    networks:
      - internal
    volumes:
      - /dev:/dev
    cap_add:
      - SYS_ADMIN
    privileged: true
  client:
    image: daos_client
    tty: true
    networks:
      - internal
    volumes:
      - /dev:/dev
    cap_add:
      - SYS_ADMIN
    privileged: true

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
